#!/usr/bin/env ruby

class Logo

  def initialize(grid_size, program)
    @grid_size = grid_size
    @program = program
    @grid = []
    # setup_grid
    # print_grid
    parse
  end

  def setup_grid
    @grid_size.times do |i|
      row = []
      @grid_size.times do |j|
        row << "."
      end
      @grid << row
    end
  end

  def parse
    commands = @program.split
    stack = []
    i = 0 
    while i < commands.size
      if %w[FD RT LT BK].include?(commands[i]) 
        stack << [commands[i], commands[i + 1]] 
        i += 2
      elsif commands[i] == "REPEAT"
        repeat = []
        while commands[i] != "]"
          if %w[FD RT LT BK].include?(commands[i]) 
            repeat << [commands[i], commands[i + 1]] 
          end
        end
        stack << ["REPEAT", commands[i + 1], repeat] 
        i += 2
      else
        i += 1
      end
    end 
    puts stack.inspect
  end

  def print_grid
    puts @grid.map{|row| row.join("")}.join("\n")
  end

end

filename = ARGV[0]
if File.exists?(filename)
  data = File.read(filename)
  grid_size, program = data.split("\n\n")
  Logo.new(grid_size.to_i, program)
else
  puts "error:could not read file #{filename}."
end



